/**
 * Generate the tree-shakable `unicode-picker/data` provider from
 * `@unicode/unicode-17.0.0`:
 *   providers/data/blocks/<slug>.ts   one PickerBlock export per block
 *   providers/data/emoji.ts           curated Emoji export
 *   providers/data/index.ts           barrel + `blocks` + `all`
 *
 * Run with: npm run gen:data
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadBlocks, loadEmoji, type SourceBlock } from './unicode-source';

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(HERE, '..', 'providers', 'data');
const BLOCKS_DIR = join(DATA_DIR, 'blocks');
function moduleSource(b: SourceBlock, depth: '..' | '../..'): string {
  const typesImport = `import type { PickerBlock } from '${depth}/../src/data/types';`;
  const runtimeImport = depth === '../..' ? '../runtime' : './runtime';
  if (b.large) {
    // Range-encoded, no names — keeps giant blocks (CJK, etc.) tiny.
    const meta = { name: b.name, range: b.range };
    return (
      `${typesImport}\n` +
      `import { expand } from '${runtimeImport}';\n\n` +
      `export const ${b.exportId}: PickerBlock = {\n` +
      `  name: ${JSON.stringify(meta.name)},\n` +
      `  range: ${JSON.stringify(meta.range)},\n` +
      `  characters: expand(${JSON.stringify(b.ranges)}),\n` +
      `};\n`
    );
  }
  const characters = b.chars.map((c) => (c.name ? { char: c.char, name: c.name } : c.char));
  const block = { name: b.name, range: b.range, characters };
  return `${typesImport}\n\nexport const ${b.exportId}: PickerBlock = ${JSON.stringify(block)};\n`;
}

function main(): void {
  const blocks = loadBlocks();
  const emoji = loadEmoji();

  rmSync(BLOCKS_DIR, { recursive: true, force: true });
  mkdirSync(BLOCKS_DIR, { recursive: true });

  for (const b of blocks) {
    writeFileSync(join(BLOCKS_DIR, `${b.slug}.ts`), moduleSource(b, '../..'));
  }
  writeFileSync(join(DATA_DIR, 'emoji.ts'), moduleSource(emoji, '..'));

  // Barrel: individual tree-shakable re-exports + a heavy `all`/`blocks`.
  const imports = blocks
    .map((b) => `import { ${b.exportId} } from './blocks/${b.slug}';`)
    .join('\n');
  const reexports = blocks
    .map((b) => `export { ${b.exportId} } from './blocks/${b.slug}';`)
    .join('\n');
  const list = blocks.map((b) => b.exportId).join(', ');

  const index =
    `// GENERATED by scripts/gen-data.ts — do not edit by hand.\n` +
    `import type { PickerBlock } from '../../src/data/types';\n` +
    `${imports}\n\n` +
    `export type { PickerBlock } from '../../src/data/types';\n` +
    `export { emoji } from './emoji';\n` +
    `${reexports}\n\n` +
    `/** Every Unicode block, in code-point order (heavy — opts out of tree-shaking). */\n` +
    `export const blocks: PickerBlock[] = [${list}];\n\n` +
    `/** Alias for {@link blocks}: the full dataset. */\n` +
    `export const all: PickerBlock[] = blocks;\n`;
  writeFileSync(join(DATA_DIR, 'index.ts'), index);

  const total = blocks.reduce((n, b) => n + b.count, 0) + emoji.count;
  console.log(
    `Generated ${blocks.length} blocks + emoji (${emoji.count}) — ${total} characters total.`
  );
}

main();
